export const CODE = ["let ReactNativeEventTypes;",
"if (Platform.OS === 'ios') {",
"  ReactNativeEventTypes = {",
"    customBubblingEventTypes: IOS_BUBBLING_EVENT_TYPES,",
"    customDirectEventTypes: IOS_DIRECT_EVENT_TYPES,",
"  };",
"} else if (Platform.OS === 'android') {",
"  ReactNativeEventTypes = {",
"    customBubblingEventTypes: ANDROID_BUBBLING_EVENT_TYPES,",
"    customDirectEventTypes: ANDROID_DIRECT_EVENT_TYPES,",
"  };",
"}"].join("\n");
// export const CODE = ["let ReactNativeEventTypes;",
// "if (Platform.OS === 'ios') {",
// "  ReactNativeEventTypes = {",
// "    customBubblingEventTypes: IOS_BUBBLING_EVENT_TYPES,",
// "    customDirectEventTypes: IOS_DIRECT_EVENT_TYPES,",
// "  };",
// "} else if (Platform.OS === 'android') {",
// "  ReactNativeEventTypes = {",
// "    customBubblingEventTypes: ANDROID_BUBBLING_EVENT_TYPES,",
// "    customDirectEventTypes: ANDROID_DIRECT_EVENT_TYPES,",
// "  };",
// "} else {",
// "  ReactNativeEventTypes = {",
// "    customBubblingEventTypes: emptyObject,",
// "    customDirectEventTypes: emptyObject,",
// "  };",
// "}"].join("\n");
